server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/indentity_service
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "42ee2bcf152755232802d8b059a36825ceb094e9b6da85e6fdd70a4685706170330b48ccbc884dd2b05ad82dd7ff4f01a24b5ca47d82bff7e5b19ad9a9083bc0"